export const FETCH_SUCCESS_GET_ALL_MOVIES = 'FETCH_SUCCESS_GET_ALL_MOVIES';

export const FETCH_SUCCESS_GET_SPECIAL_MOVIE = 'FETCH_SUCCESS_GET_SPECIAL_MOVIE';

export const START_SEARCH_MOVIES = 'START_SEARCH_MOVIES';
export const SUCCESS_SEARCH_MOVIES = 'SUCCESS_SEARCH_MOVIES';
export const ERROR_SEARCH_MOVIES = 'ERROR_SEARCH_MOVIES';

export const SUCCESS_GET_FROM_LS = 'SUCCESS_GET_FROM_LS';
export const SUCCESS_GET_WATCH_LATER = 'SUCCESS_GET_WATCH_LATER';

