export const FETCH_START = 'FETCH_START';
export const FETCH_SUCCESS_GET_ALL_MOVIES = 'FETCH_SUCCESS_GET_ALL_MOVIES';
export const FETCH_ERROR_GET_ALL_MOVIES = 'FETCH_ERROR_GET_ALL_MOVIES';

export const FETCH_START_SPECIAL_MOVIE = 'FETCH_START_SPECIAL_MOVIE';
export const FETCH_SUCCESS_GET_SPECIAL_MOVIE = 'FETCH_SUCCESS_GET_SPECIAL_MOVIE';
export const FETCH_ERROR_GET_SPECIAL_MOVIE = 'FETCH_ERROR_GET_SPECIAL_MOVIE';

export const START_SEARCH_MOVIES = 'START_SEARCH_MOVIES';
export const SUCCESS_SEARCH_MOVIES = 'SUCCESS_SEARCH_MOVIES';
export const ERROR_SEARCH_MOVIES = 'ERROR_SEARCH_MOVIES';

