export { default as Like} from './Like'
export { default as Friends} from './Friends'
export { default as View} from './View'
export { default as Star} from './Star'
export { default as Music} from './Music'
export { default as SearchIcon} from './SearchIcon'
export { default as Language} from './Language'